security:
  basic:
    enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/security
    username: root
    password: root
demo:
  security:
    browser:
#      loginPage: /demo-signIn.html
      loginPage: signIn.html
    code:
      image:
        width: 67
        height: 23
        length: 4
        expireIn: 60
        url: /user,/user/*  #需要验证码的的接口
    social:
      filterProcessesUrl: /login
      qq:
        app-id: 101386962
        app-secret: 2a0f820407df400b84a854d054be8b6a
        providerId: qq