security:
  basic:
    enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/test
    username: root
    password: 128000
demo:
  security:
    browser:
      loginPage: /demo-signIn.html
    code:
      image:
        width: 82
        length: 6